from typing import Dict, List, Tuple

class Point:
    def __init__(self, x: float, y: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    def to_tuple(self) -> Tuple[float, float]: ...

class Size:
    def __init__(self, width: float, height: float) -> None: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def to_tuple(self) -> Tuple[float, float]: ...

class Rect:
    def __init__(self, x: float, y: float, width: float, height: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    def to_tuple(self) -> Tuple[float, float, float, float]: ...

class PatternId:
    def __init__(self, value: str) -> None: ...
    def as_str(self) -> str: ...

class RuntimeId:
    def __init__(self, value: str) -> None: ...
    def as_str(self) -> str: ...

class TechnologyId:
    def __init__(self, value: str) -> None: ...
    def as_str(self) -> str: ...

class Namespace:
    Control: 'Namespace'
    Item: 'Namespace'
    App: 'Namespace'
    Native: 'Namespace'
    def as_str(self) -> str: ...
    def is_default(self) -> bool: ...

def all_namespaces() -> List[Namespace]: ...
def resolve_namespace(prefix: str | None) -> Namespace: ...

def attribute_names() -> Dict[str, Dict[str, str]]: ...

