from typing import Any, List, TypedDict, Tuple, overload, Literal
from . import core

class ProviderError(Exception): ...
class EvaluationError(Exception): ...

class EvaluatedAttribute(TypedDict):
    type: str  # always "attr"
    owner: 'Node'
    namespace: str
    name: str
    value: Any

class NodeAttribute(TypedDict):
    namespace: str
    name: str
    value: Any

class Node:
    @property
    def runtime_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def role(self) -> str: ...
    @property
    def namespace(self) -> core.Namespace: ...
    def attribute(self, name: str, namespace: str | None = ...) -> Any: ...
    def parent(self) -> 'Node | None': ...
    def children(self) -> list['Node']: ...
    def attributes(self) -> list[NodeAttribute]: ...
    def supported_patterns(self) -> list[str]: ...
    def doc_order_key(self) -> int | None: ...
    def invalidate(self) -> None: ...
    def pattern_by_id(self, id: str) -> object | None: ...
    def has_pattern(self, id: str) -> bool: ...
    def pattern_by_id(self, id: str) -> object | None: ...
    def has_pattern(self, id: str) -> bool: ...

class Focusable:
    def id(self) -> str: ...
    def focus(self) -> None: ...

class WindowSurface:
    def id(self) -> str: ...
    def activate(self) -> None: ...
    def minimize(self) -> None: ...
    def maximize(self) -> None: ...
    def restore(self) -> None: ...
    def close(self) -> None: ...
    def move_to(self, x: float, y: float) -> None: ...
    def resize(self, width: float, height: float) -> None: ...
    def move_and_resize(self, x: float, y: float, width: float, height: float) -> None: ...
    def accepts_user_input(self) -> bool | None: ...

class Runtime:
    def __init__(self) -> None: ...
    def evaluate(self, xpath: str, node: 'Node | None' = ...) -> List[Any]: ...
    def shutdown(self) -> None: ...
    def pointer_position(self) -> core.Point: ...
    @overload
    def pointer_move_to(self, point: core.Point, /, overrides: 'PointerOverridesDict | None' = ...) -> core.Point: ...
    @overload
    def pointer_move_to(self, point: Tuple[float, float], /, overrides: 'PointerOverridesDict | None' = ...) -> core.Point: ...
    @overload
    def pointer_click(self, point: core.Point, /, button: Literal['left','middle','right'] | None = ..., overrides: 'PointerOverridesDict | None' = ...) -> None: ...
    @overload
    def pointer_click(self, point: Tuple[float, float], /, button: Literal['left','middle','right'] | None = ..., overrides: 'PointerOverridesDict | None' = ...) -> None: ...
    @overload
    def pointer_multi_click(self, point: core.Point, /, clicks: int, button: Literal['left','middle','right'] | None = ..., overrides: 'PointerOverridesDict | None' = ...) -> None: ...
    @overload
    def pointer_multi_click(self, point: Tuple[float, float], /, clicks: int, button: Literal['left','middle','right'] | None = ..., overrides: 'PointerOverridesDict | None' = ...) -> None: ...
    @overload
    def pointer_drag(self, start: core.Point, /, end: core.Point, button: Literal['left','middle','right'] | None = ..., overrides: 'PointerOverridesDict | None' = ...) -> None: ...
    @overload
    def pointer_drag(self, start: Tuple[float, float], /, end: Tuple[float, float], button: Literal['left','middle','right'] | None = ..., overrides: 'PointerOverridesDict | None' = ...) -> None: ...
    def keyboard_type(self, sequence: str, overrides: 'KeyboardOverridesDict | None' = ...) -> None: ...
    def keyboard_press(self, sequence: str, overrides: 'KeyboardOverridesDict | None' = ...) -> None: ...
    def keyboard_release(self, sequence: str, overrides: 'KeyboardOverridesDict | None' = ...) -> None: ...

class PointerOverridesDict(TypedDict, total=False):
    origin: str | Tuple[float, float] | Tuple[float, float, float, float] | dict
    speed_factor: float
    acceleration_profile: Literal['constant','ease_in','ease_out','smooth_step']
    max_move_duration_ms: float
    move_time_per_pixel_us: float
    after_move_delay_ms: float
    after_input_delay_ms: float
    press_release_delay_ms: float
    after_click_delay_ms: float
    before_next_click_delay_ms: float
    multi_click_delay_ms: float
    ensure_move_threshold: float
    ensure_move_timeout_ms: float
    scroll_step: Tuple[float, float]
    scroll_delay_ms: float

class KeyboardOverridesDict(TypedDict, total=False):
    press_delay_ms: float
    release_delay_ms: float
    between_keys_delay_ms: float
    chord_press_delay_ms: float
    chord_release_delay_ms: float
    after_sequence_delay_ms: float
    after_text_delay_ms: float
