from typing import Any, List, Tuple, Literal, Union, Dict, TypeAlias
import enum as _enum
from . import core

class ProviderError(Exception): ...
class EvaluationError(Exception): ...
class PointerError(Exception): ...
class KeyboardError(Exception): ...
class PatternError(Exception): ...

# Value types returned by attributes/evaluation
Primitive: TypeAlias = Union[bool, int, float, str, None]
JSONLike: TypeAlias = Union[Dict[str, Any], List[Any]]
Complex: TypeAlias = Union[core.Point, core.Size, core.Rect]
UiValue: TypeAlias = Union[Primitive, JSONLike, Complex]

# Helper aliases for concise signatures
PointLike: TypeAlias = core.Point
OriginLike: TypeAlias = Union[Literal['desktop'], core.Point, core.Rect]
ScrollDeltaLike: TypeAlias = Tuple[float, float]
class PointerButton(_enum.IntEnum):
    LEFT = 1
    MIDDLE = 2
    RIGHT = 3

ButtonLike: TypeAlias = Union[int, PointerButton]

class UiAttribute:
    @property
    def namespace(self) -> str: ...
    @property
    def name(self) -> str: ...
    def value(self) -> UiValue | None: ...

class EvaluatedAttribute:
    @property
    def namespace(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> UiValue: ...
    def owner(self) -> 'UiNode | None': ...

class UiNode:
    @property
    def runtime_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def role(self) -> str: ...
    @property
    def namespace(self) -> core.Namespace: ...
    def attribute(self, name: str, namespace: str | None = ...) -> UiValue: ...
    def parent(self) -> 'UiNode | None': ...
    def children(self) -> list['UiNode']: ...
    def attributes(self) -> list[UiAttribute]: ...
    def supported_patterns(self) -> list[str]: ...
    def doc_order_key(self) -> int | None: ...
    def invalidate(self) -> None: ...
    def pattern_by_id(self, id: str) -> object | None: ...
    def has_pattern(self, id: str) -> bool: ...

class Focusable:
    def id(self) -> str: ...
    def focus(self) -> None: ...

class WindowSurface:
    def id(self) -> str: ...
    def activate(self) -> None: ...
    def minimize(self) -> None: ...
    def maximize(self) -> None: ...
    def restore(self) -> None: ...
    def close(self) -> None: ...
    def move_to(self, x: float, y: float) -> None: ...
    def resize(self, width: float, height: float) -> None: ...
    def move_and_resize(self, x: float, y: float, width: float, height: float) -> None: ...
    def accepts_user_input(self) -> bool | None: ...

class Runtime:
    def __init__(self) -> None: ...
    def evaluate(self, xpath: str, node: 'UiNode | None' = ...) -> List[Union[UiNode, EvaluatedAttribute, UiValue]]: ...
    def shutdown(self) -> None: ...
    def desktop_node(self) -> UiNode: ...
    def desktop_info(self) -> Dict[str, Any]: ...
    def focus(self, node: UiNode) -> None: ...
    def pointer_position(self) -> core.Point: ...
    def pointer_move_to(self, point: PointLike, /, overrides: 'PointerOverrides | None' = ...) -> core.Point: ...
    def pointer_click(self, point: PointLike, /, button: ButtonLike | None = ..., overrides: 'PointerOverrides | None' = ...) -> None: ...
    def pointer_multi_click(self, point: PointLike, /, clicks: int, button: ButtonLike | None = ..., overrides: 'PointerOverrides | None' = ...) -> None: ...
    def pointer_drag(self, start: PointLike, /, end: PointLike, button: ButtonLike | None = ..., overrides: 'PointerOverrides | None' = ...) -> None: ...
    def pointer_press(self, point: PointLike | None = ..., button: ButtonLike | None = ..., overrides: 'PointerOverrides | None' = ...) -> None: ...
    def pointer_release(self, button: ButtonLike | None = ..., overrides: 'PointerOverrides | None' = ...) -> None: ...
    def pointer_scroll(self, delta: ScrollDeltaLike, overrides: 'PointerOverrides | None' = ...) -> None: ...
    def keyboard_type(self, sequence: str, overrides: 'KeyboardOverrides | None' = ...) -> None: ...
    def keyboard_press(self, sequence: str, overrides: 'KeyboardOverrides | None' = ...) -> None: ...
    def keyboard_release(self, sequence: str, overrides: 'KeyboardOverrides | None' = ...) -> None: ...
class PointerOverrides:
    def __init__(
        self,
        *,
        origin: OriginLike | None = ...,
        speed_factor: float | None = ...,
        acceleration_profile: Literal['constant','ease_in','ease_out','smooth_step'] | None = ...,
        max_move_duration_ms: float | None = ...,
        move_time_per_pixel_us: float | None = ...,
        after_move_delay_ms: float | None = ...,
        after_input_delay_ms: float | None = ...,
        press_release_delay_ms: float | None = ...,
        after_click_delay_ms: float | None = ...,
        before_next_click_delay_ms: float | None = ...,
        multi_click_delay_ms: float | None = ...,
        ensure_move_threshold: float | None = ...,
        ensure_move_timeout_ms: float | None = ...,
        scroll_step: Tuple[float, float] | None = ...,
        scroll_delay_ms: float | None = ...,
    ) -> None: ...
    @property
    def origin(self) -> Literal['desktop'] | core.Point | core.Rect | None: ...
    @property
    def speed_factor(self) -> float | None: ...
    @property
    def acceleration_profile(self) -> Literal['constant','ease_in','ease_out','smooth_step'] | None: ...
    @property
    def max_move_duration_ms(self) -> float | None: ...
    @property
    def move_time_per_pixel_us(self) -> float | None: ...
    @property
    def after_move_delay_ms(self) -> float | None: ...
    @property
    def after_input_delay_ms(self) -> float | None: ...
    @property
    def press_release_delay_ms(self) -> float | None: ...
    @property
    def after_click_delay_ms(self) -> float | None: ...
    @property
    def before_next_click_delay_ms(self) -> float | None: ...
    @property
    def multi_click_delay_ms(self) -> float | None: ...
    @property
    def ensure_move_threshold(self) -> float | None: ...
    @property
    def ensure_move_timeout_ms(self) -> float | None: ...
    @property
    def scroll_step(self) -> Tuple[float, float] | None: ...
    @property
    def scroll_delay_ms(self) -> float | None: ...

class KeyboardOverrides:
    def __init__(
        self,
        *,
        press_delay_ms: float | None = ...,
        release_delay_ms: float | None = ...,
        between_keys_delay_ms: float | None = ...,
        chord_press_delay_ms: float | None = ...,
        chord_release_delay_ms: float | None = ...,
        after_sequence_delay_ms: float | None = ...,
        after_text_delay_ms: float | None = ...,
    ) -> None: ...
    @property
    def press_delay_ms(self) -> float | None: ...
    @property
    def release_delay_ms(self) -> float | None: ...
    @property
    def between_keys_delay_ms(self) -> float | None: ...
    @property
    def chord_press_delay_ms(self) -> float | None: ...
    @property
    def chord_release_delay_ms(self) -> float | None: ...
    @property
    def after_sequence_delay_ms(self) -> float | None: ...
    @property
    def after_text_delay_ms(self) -> float | None: ...
